2023_06_20|11_21_26 : 0.00 : Error raised
2023_06_20|11_21_26 : Traceback (most recent call last):
  File "./main.py", line 41, in run
    cap1 = cv2.VideoCapture('/dev/'+cfg['videos'][0],cv2.CAP_V4L) # 前摄像头
IndexError: list index out of range

